# Generated by Django 3.0.5 on 2020-04-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
