# Generated by Django 3.0.5 on 2020-04-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorer', '0002_game_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
    ]
