# Generated by Django 3.0.5 on 2020-04-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorer', '0004_game_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
